language: node_js
node_js:
  - 18

cache:
  directories:
    - node_modules

before_install:
  - npm install -g expo-cli

install:
  - npm ci

script:
  - npx eslint . --ext .js,.jsx,.ts,.tsx
  - npx tsc --noEmit
  - expo diagnostics

branches:
  only:
    - main
    - develop
    - /^v\d+\.\d+\.\d+/

notifications:
  email:
    on_success: change
    on_failure: always
